name: Update Version and Create .env file

on:
  push:
    branches:
      - main # altere para o nome da sua branch principal
      - homolog
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm ci

    - name: Update version and create .env file
      env:
        GITHUB_SHA_SHORT: ${{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{github.sha}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}
      run: |
        VERSION=$(./update_version.sh) # executa o script e salva o resultado na variável VERSION
        echo "APP_VERSION=$VERSION" > .env # cria o arquivo .env com a variável APP_VERSION definida como a versão atualizada
        git add .env # adiciona o arquivo .env ao commit
        git config user.name "Seu Nome" # altere para o seu nome de usuário do GitHub
        git config user.email "seu-email@exemplo.com" # altere para o seu endereço de e-mail do GitHub
        git commit -m "Atualizar versão para $VERSION" # commita com a mensagem "Atualizar versão para X.X.X"
